# Makefile generated at Wed Aug  5 00:18:15 CST 2020

CC = gcc
CFLAGS = -Wall -g

main:	a.o aaa.o b.o bb.o c.o main.o 
	$(CC) $(CFLAGS) -o $@ a.o aaa.o b.o bb.o c.o main.o 

a.o:	a.h common.h a.c
aaa.o:	aaa.c
b.o:	b.h b.c
bb.o:	bb.h bb.c
c.o:	c.h c.c
main.o:	c.h a.h b.h main.c
