#!/bin/dash

if test -e ".shrug"
then

    for file in $@
    do 
        if test -e $file
        then
            cp "$file" ".shrug/index/"
        else
            if test -e ".shrug/index/$file"
            then
                rm -f ".shrug/index/$file"
            else
                echo "shrug-add: error: can not open '$file'"
            fi
        fi

    done

else
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
fi


