#!/bin/bash

if test -e ".shrug"
then
    echo "shrug-init: error: .shrug already exists"
else
    mkdir ".shrug"
    cd .shrug
    mkdir "index"
    mkdir ".shrug/objects"
    echo "Initialized empty shrug repository in .shrug"
fi