#!/bin/bash

if test -e ".shrug"
then

    for file in $@
    do 
        if test -e $file
        then
            cp "$file" ".shrug/index/"
        else
            echo "shrug-add: error: can not open $file"
        fi
    done

else
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
fi


