#!/bin/bash

#get the num of commit times
if test -e "./.shrug/log"
then
    num=`wc -l .shrug/log | cut -d" " -f1`
else
    num=0
    touch "./.shrug/log"
fi

message(){
    mkdir ".shrug/objects/$num"
    cp .shrug/index/* ".shrug/objects/$num"
    echo "$1" >> ./.shrug/log
    echo "Committed as commit $num"
}


if test $1 = "-m"
then
    message $2

elif test $1 = "-a" && test $2 = "-m"
then
    #echo $3
    for file in `ls .shrug/index/`
    do
        ./shrug-add $file
    done

    message "$3"

fi
