#!/bin/dash

SAVEIFS=$IFS
IFS='
'

line_num=`wc -l .shrug/log | cut -d" " -f1`
for line in $(tac .shrug/log)
do 
    line_num=`expr $line_num - 1`
    echo $line_num $line
done
# line_num=`wc -l .shrug/log | cut -d" " -f1`
# cat .shrug/log | sort -r | while read LINE
# do
#     line_num=`expr $line_num - 1`
#     echo "$line_num $LINE"
# done


# for line in `cat .shrug/log | sort -r`
# do
#     
#     echo "$line_num $line"
# done
IFS=$SAVEIFS
