#!/bin/dash

#get the num of commit times
if test -e "./.shrug/log"
then
    num=`wc -l .shrug/log | cut -d" " -f1`
else
    num=0
    touch "./.shrug/log"
fi

message(){
    if test $num -gt 0
    then
        last=`expr $num - 1` 
        if diff -i -w ".shrug/objects/$last/" ".shrug/index/" >/dev/null
        then
            echo "nothing to commit"
            exit
        fi
    fi
    mkdir ".shrug/objects/$num"

    for file in `ls .shrug/index/`
    do
        cp -u ".shrug/index/$file" ".shrug/objects/$num/"
    done
    for file in `ls .shrug/objects/$num`
    do
        if test -e ".shrug/index/$file" 
        then
            cp -u ".shrug/index/$file" ".shrug/objects/$num/"
        else
            rm -f ".shrug/objects/$num/$file"
        fi
    done
    #cp -u .shrug/index/* ".shrug/objects/$num"
    echo "$1" >> ./.shrug/log
    echo "Committed as commit $num"
}


if test $1 = "-m"
then
    message "$2"

elif test $1 = "-a" && test $2 = "-m"
then
    #echo $3
    for file in `ls .shrug/index/`
    do
        shrug-add $file
    done

    message "$3"

fi
