#!/bin/dash

if test -d ".shrug"
then
    echo "shrug-init: error: .shrug already exists"
else
    mkdir ".shrug"
    cd .shrug
    mkdir "index"
    mkdir "objects"
    echo "Initialized empty shrug repository in .shrug"
fi